### ISSUE TITLE
Idea to support hd-skins.

### ISSUE THREAD

**Issue by Khikki** [Roadhog360/Et-Futurum#12]
Hi, it's me again, sorry for duplicating the messages. I want to ask you what do you think about the 512x256 / 512x512 and 1024x512 / 1024x1024 skins? :)

Actually here is an example of how this is done in SkinPort. 
![2021-02-11_04 20 09](https://user-images.githubusercontent.com/35336209/107596746-4eff3200-6c21-11eb-88cf-da57e80df486.png)
As I recall, Optifine can do that, too. If only there was a custom host server.

And how it looks now in Et Futurum Rq.
![2021-02-11_04 15 35](https://user-images.githubusercontent.com/35336209/107596826-971e5480-6c21-11eb-9ea7-7dd863ce461a.png)

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

I decided to do this since I've been getting a lot of feature requests so I figured it'd be good to make a dedicated spot for all the requests that people want to see added
