### ISSUE TITLE
[Suggestion] Dispenser shearing sheep mechanic

### ISSUE THREAD

**Issue by Miradae** [Roadhog360/Et-Futurum#14]
After checking the feature list doc (https://docs.google.com/spreadsheets/d/1eqaYH8zMSYXEjHf7HK653l5Y5t7tcpgVnRyFx-Yeq0s/edit#gid=0) I noticed that the mechanic for dispensers shearing sheep is not added there. The mechanic was added in 1.14 (https://minecraft.gamepedia.com/Dispenser)

Would be a great addition to the mechanics of later versions

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

I decided to do this since I've been getting a lot of feature requests so I figured it'd be good to make a dedicated spot for all the requests that people want to see added
