### ISSUE TITLE
Deepslate not generating. Add dimension support for worldgen features.

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#20]
![image](https://user-images.githubusercontent.com/51277766/113346833-32aa7800-92e9-11eb-80af-8693dbc01d8f.png)
![image](https://user-images.githubusercontent.com/51277766/113346881-448c1b00-92e9-11eb-9dee-7fab3f32ba77.png)

No config changes were made to the generation. This is caused by the Lord of The Rings mod, or any others that add dimensions. Et Futurum should have dimension support.

![2021-04-01_13 51 43](https://user-images.githubusercontent.com/51277766/113347104-8917b680-92e9-11eb-9f1b-23c8da3635f6.png)

**Comment by Roadhog360** [comment]
Low priority. This was not done because deepslate is special and I'd basically have to make each dimension configurable separately which would be pretty difficult, since I don't know where the deepslate is generating, if it's in a skylands world how it'd be better with patches, or if other dimensions would even make sense to have it, because of custom stone types or another challenge already at the bottom.

**Comment by MagmaBro123** [comment]
Ah.

Well, this mod isn't too different from your average Overworld.

**Comment by Roadhog360** [comment]
Yeah. Because deepslate is a special block compared to other generated blocks I choose to handle it at a later time

**Comment by MagmaBro123** [comment]
Oh. Well, lemme know if this is added or whatnot.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Improvements" category and post your idea there so it's not mixed in with the issues tab.
