### ISSUE TITLE
Amethyst Geodes and Items/blocks related/made from it?

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#22]
Title.

**Comment by Roadhog360** [comment]
I plan on doing it once I figure out how to create a circle of blocks, lmao

**Comment by MagmaBro123** [comment]
Ah, cool.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

Decided to do this since you've got a lot of things you want to see and I figured I'd give people a place to tell me what they want to see added.
