### ISSUE TITLE
Backport 1.12's updated Creative GUI?

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#25]
Title says all. Misc. and  Materials were merged into 1 tab when 1.12 came out, and a Hotbar profile (Or whatever its called, can't remember, ugh) thing was added.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

Decided to do this since you've got a lot of things you want to see and I figured I'd give people a place to tell me what they want to see added.
