### ISSUE TITLE
Crash during Worldgen that I encounter quite a lot.

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum#35]
This is the Exception happening during Worldgen in Singleplayer:

java.lang.NullPointerException: Unexpected error
	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:176)
	at ganymedes01.etfuturum.core.handlers.ClientEventHandler.onClientTick(ClientEventHandler.java:143)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_198_ClientEventHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by GregoriusT** [comment]
I also had this one happen, during Worldgen too. Maybe do not modify your ArrayList, while you are iterating over it. ;)

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at ganymedes01.etfuturum.core.handlers.WorldTickEventHandler.tick(WorldTickEventHandler.java:83)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_215_WorldTickEventHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Roadhog360** [comment]
I am not modifying the list while already iterating. There is exactly one place that uses the list and it can only be called once at a time. This must be a Java bug.

**Comment by Speiger** [comment]
https://github.com/jss2a98aj/Et-Futurum/blob/krypt/src/main/java/ganymedes01/etfuturum/core/handlers/WorldTickEventHandler.java#L96
This actually edits the tickingTileEntitylist if the tileentity beforehand was a ticking one.

**Comment by GregoriusT** [comment]
Wait is this caused by the Village Blacksmith generating?! Does the Village Blacksmith generate lit Furnaces and if something else is somehow breaking them during the Worldgen step this crash happens, because the TileEntity is about to be unloaded?

https://github.com/jss2a98aj/Et-Futurum/blob/92207474c1c5e177a73da907daeeedec11126beb/src/main/java/ganymedes01/etfuturum/core/handlers/ClientEventHandler.java#L133-L148

Or did you change something inbetween Versions and so the Line Numbers are no longer matching up? Because this Block should never be able to throw a NullPointerException due to world or world.rand being null...

**Comment by Roadhog360** [comment]
![image](https://user-images.githubusercontent.com/11903511/118180528-a1104900-b404-11eb-8db2-dcf2ef0ed637.png)
I'll change it to this so a copy of the tile list is created instead of using the current world instance, this should fix the exception.

**Comment by Speiger** [comment]
Yeah this would fix it.
Though world.loadedTileEntityList.toArray(new TileEntity[world.loadedTileEntityList.size]); would be faster because you get "System.arraycopy" speeds. Instead of the slow improved iterator speed.

**Comment by GregoriusT** [comment]
@Speiger how could that indexed for loop "fail"? This is not really a MultiThreading Issue, this is a "List gets inadvertently modified by accessing it" Issue, meaning if its "i < size()" it should work. It would only break if you were to cache the size()

**Comment by Roadhog360** [comment]
We did an indexed for loop and I checked with Greg that the Concurrent error went away

**Comment by Speiger** [comment]
@GregoriusT its not a multithreading issue. Its singlethread issue. (Like a selfdeleting  function trying to continue to execute)

the for loop can fail because you actually can not detect if the tileentity deleted itself.
to explain:
You have 15 tileentities.
you are at index 5 and then a tileentity gets removed because of you. That means element 5 gets removed and element 6 gets shifted to element 5 now you are done and element (6)5 gets now skipped. Thats what i mean with fail. You have to kinda double/tripple check just to make sure you dont miss anything.

**Comment by GregoriusT** [comment]
Oh right now i know what shit you mean Speiger, but this is for a furnace special effect, skipping over random TileEntities is a rare edge case that can be ignored here ;)

**Comment by Roadhog360** [comment]
So today Greg suggested an indexed iterator to fix the issue with concurrent modification. I think I know why the first crash happens and I'll look into it tomorrow

**Comment by Speiger** [comment]
@GregoriusT I was referencing this:
https://github.com/Roadhog360/Et-Futurum/issues/35#issuecomment-840801149

**Comment by Roadhog360** [comment]
Yeah. In the end though for performance reasons I chose an indexed iterator to fix it, hopefully that works, as he said from testing test builds that it seemed to stop the crash where it'd normally happen

**Comment by Speiger** [comment]
@Roadhog360 yeah your solution is kinda crap for the version you are using.
You are lucky to use 1.7.10 because it has a lot of stuff that mojang dropped in 1.10.2 or newer.
Sorry for being blunt.

But you should look into IWorldAccess.markBlockForUpdate(x, y, z)
This is called whenever a setBlockCall has happened.
And you can register in the world (server sided too) and just listen to block/tileEntity changes.

On top of that you could listen to chunk load events and iterate over tileEntities in a single chunk to make sure that it was preprocessed.
That way you don't have to constantly check for stuff but just "react" to actions in the world.

Also i wouldn't process them instantly i would queue the positions up to be done in the end of the tick. That way you can filter out duplicates and also disable infinite loops.

**Comment by Roadhog360** [comment]
Ah, I see. I was just using a refined version of the tile entity loop Et Futurum originally used. How could I listen to block or Tile Entity changes? I actually tried to do that but wasn't able to find an event for it.

**Comment by Roadhog360** [comment]
Both issues have been confirmed to be fixed from me and Greg testing versions. However if you'd like me to improve the tile entity iterators, please do open a new issue and I can mark it as an enhancement. (I didn't know there were better ways so if you open an new issue please do be sure to tell me how to listen for changes properly since I wasn't able to find any events for that)

**Comment by Speiger** [comment]
@Roadhog360 if a Blockupdate happens the "block/tilentity" at a position has changed. That is your listener. (Create a Custom IWorldListener) just implement that method i just showed you. Fill it into a Set (to remove duplication checks.
Then on world tick end you just iterate over the set (cleaning it afterwards) and check if the position block/tileentity is what you want.

This only detects "user changes" and not "worldgen" thats why the "chunkload" check so you can preprocess unprocessed chunks.

Why i suggest this:
Why constantly check if you have blocks that have to be transformed even so nobody played on the server for a week but the server keeps running. You are wasting CPU time with that.
If you have a "change queue" and chunk preprocessor you reduce CPU usage massivly.

**Comment by Roadhog360** [comment]
@Speiger I don't understand at all what an IWorldListener does. What is that and how do I even register it?

**Comment by Speiger** [comment]
@Roadhog360 the world listener basically is callback on certain worldevents (just look up the function names and when they are being called)

It's main use is for Server/Client Synchronization and it is no longer there past 1.12 i think.
But since you are in 1.7.10 you don't need to worry

But it includes:
- Tracking of Audio Plays,
- Tracking of Particles
- Tracking when a Block was updated (BlockUpdate Detection)
- Tracking of Entity Spawns/Despawns
- Tracking of Mining Progress of each miner.

It is basically a tool where you can easily grab changes that you would have to brute force track otherwise.
How to register it?
In the world you want these traces checked (WorldLoadEvent for example allows you to know when a world is loaded)
you basically call: 
```java
public void loadWorldEvent(WorldEvent.Load event)
{
	event.getWorld().addWorldAccess(new MyWorldAccessImpl());
}
```
Its that simple.
The class is called: IWorldAccess and is inside the same folder the "World.class" is in.

Note: You do need to check for server/client world since you might get client data if you only care about server data so make sure you only register it in to the world you needs (WorldClient/WorldServer)

**Comment by Roadhog360** [comment]
I regret for getting to look into this sooner, this is incredibly useful information. Thank you very much for the insight.

**Comment by Roadhog360** [comment]
`
	@Override
	public void markBlockForUpdate(int x, int y, int z) {
		// TODO Auto-generated method stub

		if (replacements.isEmpty())
			return;
		
		Block replacement;
		TileEntity tile;
		
		if((replacement = replacements.get(world.getBlock(x, y, z))) == null || (tile = world.getTileEntity(x, y, z)) == null)
			return;

		NBTTagCompound nbt = new NBTTagCompound();
		tile.writeToNBT(nbt);
		if (tile instanceof IInventory) {
			IInventory invt = (IInventory) tile;
			for (int j = 0; j < invt.getSizeInventory(); j++) {
				invt.setInventorySlotContents(j, null);
			}
		}
		
		world.setBlock(x, y, z, replacement);
		TileEntity newTile = world.getTileEntity(x, y, z);
		if(newTile != null) {
			newTile.readFromNBT(nbt);
		}
			
	}`
	
	Superb. Here's what the updated code looks like.
