### ISSUE TITLE
Backport changing mob spawners via spawn eggs.

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#38]
Title.

Can't remember what version added this, but in Creative, right-clicking a mob spawner with any spawn egg would change the spawner's type to whatever mob that egg spawns. So if I wanted a Nitro Creeper Spawner (Natura) I could just click a spawner with the respective spawn egg.

There's pretty much no mob spawner changing mods. And this is a feature in newer versions.

**Comment by MagmaBro123** [comment]
@DarianLStephens Why the eyes?

**Comment by DarianLStephens** [comment]
Because it's interesting, I guess?

**Comment by MagmaBro123** [comment]
> Because it's interesting, I guess?

Ah.

**Comment by tyrael93** [comment]
Isn't this a thing already? I could have sworn I could do this in creative.

**Comment by MagmaBro123** [comment]
> Isn't this a thing already? I could have sworn I could do this in creative.

I tried and never worked.

**Comment by Roadhog360** [comment]
I didn't notice this wasn't in 1.7. I've gotta add this.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

Decided to do this since you've got a lot of things you want to see and I figured I'd give people a place to tell me what they want to see added.

(PS, I tried adding this and had a bit of trouble, I'm starting to think this isn't possible under 1.7.10)
