### ISSUE TITLE
Backport the 1.9x food regen system.

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#43]
Not really sure how to explain it, but in 1.9x food gave the player high health regen.

**Comment by DarianLStephens** [comment]
It makes you expend saturation to regenerate extremely quickly, at least to a point.

**Comment by MagmaBro123** [comment]
Ah. Couldn't remember what they changed.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Ideas" category and post your idea there so it's not mixed in with the issues tab.

Decided to do this since you've got a lot of things you want to see and I figured I'd give people a place to tell me what they want to see added.
