### ISSUE TITLE
Make Elytras useable rather than an unusable cape thing.

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#44]

**Comment by Roadhog360** [comment]
A merge with Backlytra is planned

**Comment by MagmaBro123** [comment]
Ah, mk.

**Comment by MagmaBro123** [comment]
Looking at Backlytra, it does have quite a few bugs in terms of rendering & such.

**Comment by Roadhog360** [comment]
Do you think I'm not going to attempt to fix them? I don't know why every time I tell people about the merge they bring up the bugs.

**Comment by MagmaBro123** [comment]
Ah, sorry.

**Comment by Roadhog360** [comment]
You're fine. Sorry if anything I say comes off as rash; I promise I don't mean it but I figured I might be coming off that way since you're apologising a lot.

I'll try to fix the bugs with the way the mod works so it's less buggy finctionally. I'm not good with rendering though, rendering issues might be less likely to get fixed but I do want to see what I can fix about elytra physics being buggy

**Comment by MagmaBro123** [comment]
And the fireworks boosting thing.
