### ISSUE TITLE
Cobbled deepslate crafts regular cobblestone slabs

### ISSUE THREAD

**Issue by KibaTheBarbarian** [Roadhog360/Et-Futurum#50]
Cobblestone deep slate makes Cobblestone slabs

**Comment by KibaTheBarbarian** [comment]
other bug I just recently discovered your 1.8 Minecraft skin config does work but if Smart moving's in the pack the player skin freaks out

**Comment by Roadhog360** [comment]
> other bug I just recently discovered your 1.8 Minecraft skin config does work but if Smart moving's in the pack the player skin freaks out

This should be a separate report

**Comment by DelirusCrux** [comment]
Ahh that's the ore dictionary taking priority in recipes, sometimes the ore dictionary can be frustrating :D

**Comment by Roadhog360** [comment]
Yeah.
Unregistering any conflicting recipes, adding your own and then re-adding the removed vanilla recipe usually solves it.

**Comment by DelirusCrux** [comment]
Or you add recipes with your own recipe Class extending ShapedOre or ShapelessOre recipe classes and register those to load before the minecraft shaped classes, so your recipes added will take priority. Greg told me how to do it and it works nicely

**Comment by GregoriusT** [comment]
Ah right, that one I told you about, maybe I should add that Recipe thing myself once I am no longer melting in the Summer Heat. :D

**Comment by Roadhog360** [comment]
Wait, you can do that and it'll take priority without unregistering recipes?

**Comment by GregoriusT** [comment]
Yes, you can make it so Forge sorts the Crafting Recipe List so that your specific Recipes come first and OreDict Recipes come afterwards. It is already how it does Shaped Recipes first and Shapeless after. I told DelirusCrux about it and it worked for her.

It is lovely how the inefficiency of Crafting Recipes being a huge iterated List, can still be exploited in such a way as to make this kind of Recipes work.

**Comment by Roadhog360** [comment]
Fix pending release
